# Generated by Django 3.1.7 on 2021-07-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='follow',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=True),
        ),
    ]
